version: '3'
services:
  ib:
    image: twhtanghk/ibcp
    ports:
      - 5000
    env_file:
      - ../.env

  node:
    image: node
    volumes:
      - ./src:/root
    env_file:
      - ../.env
      - ./.env
    command: npm test
